### ISSUE TITLE
Установка ключевых библиотек и интеграции

### ISSUE THREAD

**Issue by AlexanderTsarkov** [AlexanderTsarkov/AirLink_Mobile#3]
1. В `pubspec.yaml` добавить зависимости:
   ```yaml
   dependencies:
     mapbox_maps_flutter: ^2.8.0      # карты и 3D-визуализация
     geolocator: ^14.0.1             # геолокация
     sensors_plus: ^6.1.1            # акселерометр, гироскоп, барометр
     dio: ^5.8.0+1                   # HTTP-клиент
     flutter_dotenv: ^5.2.1          # .env
     hooks_riverpod: ^2.6.1          # управление состоянием
     intl: ^0.20.2                   # локализация
     retrofit: ^4.4.2                # API-клиент для OpenWeather
     json_serializable: ^6.9.5       # генерация моделей
     logger: ^2.5.0                  # логирование
   dev_dependencies:
     flutter_test:
     mocktail: ^1.0.4
   ```
2. Создать пример файла `.env` с ключами:
   ```env
   OPENWEATHER_API_KEY=...
   MAPBOX_ACCESS_TOKEN=...
   ```
3. Настроить работу с локализацией:
   - ARB-файлы
   - `flutter_localizations`
4. Провести пробный запрос к OpenWeather API и отобразить карту Mapbox.

---

**Инструкции для AI-разработчика:**
- Перед началом каждого шага ознакомиться с `docs/dev/AI_Developer_Guidelines.md` и существующим кодом.
- После выполнения каждого шага представить отчёт и план для следующего.
- Обосновывать выбор инструментов и версий библиотек.
- Соблюдать модульность и переиспользование компонентов.
- Согласовывать ключевые решения с заказчиком — Alexander Tsarkov.
